### PR TITLE
Adding support for Binary Row Keys 

### PR DESCRIPTION
**Pull request by apsaltis**
Adding support for Binary Row Keys for both PutHBaseCell and PutHBaseJSON. This also involved making changes to PutFlowFile and PutColumn to carry around byte[] and not all strings. These changes are per JIRA NIFI-2620

### CODE REVIEW

File: nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/main/java/org/apache/nifi/hbase/AbstractPutHBase.java [hunk 1]
```diff
@@ -170,7 +193,7 @@ public void onTrigger(final ProcessContext context, final ProcessSession session
     }
 
     protected String getTransitUri(PutFlowFile putFlowFile) {
-        return "hbase://" + putFlowFile.getTableName() + "/" + putFlowFile.getRow();
+        return "hbase://" + putFlowFile.getTableName() + "/" + new String(putFlowFile.getRow());
```
Comment (bbende) [inline nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/main/java/org/apache/nifi/hbase/AbstractPutHBase.java]: we may want to do `new String(putFlowFile.getRow(), StandardCharsets.UTF8)` just to be safe

File: nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/main/java/org/apache/nifi/hbase/PutHBaseCell.java [hunk 2]
```diff
@@ -82,8 +84,19 @@ public void process(final InputStream in) throws IOException {
...
         });
 
-        final Collection<PutColumn> columns = Collections.singletonList(new PutColumn(columnFamily, columnQualifier, buffer));
-        return new PutFlowFile(tableName, row, columns, flowFile);
+
+        final Collection<PutColumn> columns = Collections.singletonList(new PutColumn(columnFamily.getBytes(StandardCharsets.UTF_8),
+                                                                            columnQualifier.getBytes(StandardCharsets.UTF_8), buffer));
+
+        //check to see if we need to modify the rowKey before we pass it down to the PutFlowFile
+        byte[] rowKeyBytes = null;
```
Comment (bbende) [inline nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/main/java/org/apache/nifi/hbase/PutHBaseCell.java]: Might be able to create a utility method in the abstract class like `byte[] getRow(String row, String encoding)` since it looks PutHBaseCell and PutHBaseJson both need the same logic

File: nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/test/java/org/apache/nifi/hbase/MockHBaseClientService.java [hunk 3]
```diff
@@ -131,4 +131,48 @@ public void setThrowException(boolean throwException) {
     public byte[] toBytes(final String s) {
         return s.getBytes(StandardCharsets.UTF_8);
     }
+
+    @Override
+    //Implementation of this and the isHexDigit and toBinaryFromHex are from HBase Bytes.java
+    public byte[] toBytesBinary(String s) {
```
Comment (bbende) [inline nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/test/java/org/apache/nifi/hbase/MockHBaseClientService.java]: I'm wondering if we should declare a test dependency on HBase 1.1.2 so that we don't need to copy this code, or if its better/easier to just copy this code we might need to put something in our notice or license to attribute it

**Comment by bbende** [comment]
Overall this looks good, thanks Andrew! 

One overall comment is that we now have several places where we create a new string from a byte[] like `new String(byte[])` and I think we want to specify the charset in those cases

**Comment by bbende** [comment]
Thanks for making the updates, looks good, testing it now... I noticed this PR is against 0.x, since most new development is going into 1.x, should we put this into master?

I think the changes should apply cleanly against master so we don't have to close and re-open the PR, but just wanted to confirm where it will get merged in. Thanks.

**Comment by apsaltis** [comment]
Bryan,
Thanks for the review. This is certainly new development and thus I agree that this should be put into master

**Comment by bbende** [comment]
Tested and all looks good, will merge to master, thanks Andrew!

**Comment by a-aravindan** [comment]
Hi All,
This nifi-**-nar-0.6.1.nar created for this request is not working with HDP 2.3.4. It is throwing the ERROR "failed to process due to java.lang.NoSuchMethodError: org.apache.nifi.hbase.put.PutColumn."
nar files used:
nifi-standard-services-api-nar-0.6.1.nar 
nifi-hbase-nar-0.6.1.nar 
nifi-hbase_1_1_2-client-service-nar-0.6.1.nar

Thanks
Aravind
